### ISSUE TITLE
Setting up SetHomes is absurdly difficult

### ISSUE THREAD

**Issue by lebbe** [Xquiset/SetHomes#10]
SetHomes require Vault, and using Vault again requires to use a permissions-plugin supported by Vault.

Vault lists a set of permissions plugins that it supports but **a)** They seem really outdated (except one) and **b)** None of the links works. So after quite some time with fiddling, I end up installing Vault and GroupManager (removing LuckPerms since this is not on the list of permission plugins Vault supports). Then, after running these two commands, SetHomes start to work:

```
mangaddp default homes.home
mangaddp default homes.sethome
```

After all the frustration and investigation, Im writing this here for other frustrated people to se. I would like to know what setup the developer of  this plugin is using for testing. And perhaps the Readme.md can be updated with instructions like these, so it is easier for the next person to start using SetHomes :) 

The permissiongs plugins supported by Vault, and their status (according to first link I find after Googling):

- Permissions 3, stopped updating **2011**
- bPermissions, last update over a year ago
- PEX, is PermissionsEx, but impossible to know if your not into the "lingo". This is currently unsupported, and links you to LuckPerms. But LuckPerms is _NOT_ supported by Vault (I know because LuckPerms happen to be the permission plugin I currently use, and sethomes does not support setting of more than the 0 non-named default home)
- GroupManager, is still updated and supported!!
- PermissionsBukkit, not updated since 2016
- zPermission, cannot find out what this references....
- SimplyPerms, last updated 2012
- Privileges, last updated 2013
- DroxPerms, last updated 2013
- xPerms, last updated 2013

**Comment by Xquiset** [comment]
Hello,

Thank you for taking the time to write this up and explain your frustrations. I have just uploaded SetHomes V1.2.9 to
[https://dev.bukkit.org/projects/set-homes](https://dev.bukkit.org/projects/set-homes), and am awaiting approval of the file. Once it becomes approved for download by the public you should find that installation and setup is now much less of a hassle. I have added support for LuckPerms, and left Vault as the backup option. Also if neither of these options are found then the plugin will continue to load, however the max-homes support becomes disabled since it is a group setting, rather than player by player. I hope these updates will remove some of the frustrations you and others have expressed about the use of Vault.

Thank you again,
Xquiset
