### ISSUE TITLE
naming a home "." will break all home commands for a user

### ISSUE THREAD

**Issue by thingy237** [Xquiset/SetHomes#14]
One of my players named their home "." and broke all home commands for them, I can't see their home list when typing /homes <player>. How can I reset their homes?

**Comment by Xquiset** [comment]
Hello,

Another user of the plugin has pointed out that I forgot to add validation when the player enters a home name. I have just uploaded a new version of the plugin today (SetHomes V1.3.0) that fixes this issue. In order to fix your players home you will need to search your homes.yml located at, "plugins > SetHomes > homes.yml", for this specific players UUID and either change the name of the home or just remove it from the config all together. Please let me know if there is anything else I can help you with.

Best Regards,
Xquiset
