### ISSUE TITLE
Players unable to set more than one home.

### ISSUE THREAD

**Issue by ValianceZ** [Xquiset/SetHomes#3]
So this plugin has recently been added to my friend's server, and it seems that un-opped players are unable to set more than one home, with it saying "You don't have permission to do that", and have not seen anything in the config that would disallow this. For reference, the only thing that seems to show in the config file are the homes already set, and was wondering how to go about fixing this issue.

**Comment by Xquiset** [comment]
This is easily fixed by adding a permissions plugin. The one I use to test is called PermissionsEx. If the server owner installs this then they can use this command to give players the permission for multiple homes. /pex user <PlayerName> add homes.sethome. If you want to allow all commands for a player use homes.* instead of homes.sethome.

Beat Regards,
Xquiset
