### ISSUE TITLE
Fails to load up at "getMaxHomes"

### ISSUE THREAD

**Issue by LilacTimes** [Xquiset/SetHomes#5]
The Plugin sadly fails to load. 
We're running on paper, 1.16.1, Vault and LuckPerms (which is what handles permissions with Vault), all updated to their newest versions and whatnot.

I really have no idea what is causing it to fail, other than it having to do with getMaxHomes. 
(at com.samleighton.xquiset.sethomes.SetHomes.getMaxHomes(SetHomes.java:249) ~[?:?])

A full list of all our plugins and the SetHomes load-up error here
https://pastebin.com/6sTStQEQ

Hope ya can help out, fam

**Comment by Xquiset** [comment]
Hello,

I believe the issue here is that you're using LuckPerms. This permission plugin is not actually supported by "Vault" which is causing the error when SetHomes tries to read the max-homes setting, from config, for a group. I recommend that you take a look at the officially supported Permission plugins list found on "Vaults" page here: [https://dev.bukkit.org/projects/vault](https://dev.bukkit.org/projects/vault) Please try using one of the listed permission plugins from their page, and see if the issue still persists. Sorry for any trouble this may have caused.

Best Regards,
Xquiset

**Comment by Xquiset** [comment]
Hi,
This issue has been open for almost two weeks if I don’t get an update from you in 5 days then I will be closing this issue.
Best Regards,
Xquiset
